/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simperkas;
import kelas.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import javax.net.ssl.SSLSession;
import javax.swing.JOptionPane;
import kelas.Session;

/**
 *
 * @author Nabila
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tUSERNAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tMASUK = new javax.swing.JButton();
        tRESET = new javax.swing.JButton();
        tPASSWORD = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tUSERNAME.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tUSERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUSERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(tUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 90, -1));

        tMASUK.setBackground(new java.awt.Color(0, 51, 153));
        tMASUK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tMASUK.setForeground(new java.awt.Color(255, 255, 255));
        tMASUK.setText("LOGIN");
        tMASUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMASUKActionPerformed(evt);
            }
        });
        getContentPane().add(tMASUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 260, 40));

        tRESET.setBackground(new java.awt.Color(204, 0, 51));
        tRESET.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tRESET.setForeground(new java.awt.Color(255, 255, 255));
        tRESET.setText("RESET");
        tRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRESETActionPerformed(evt);
            }
        });
        getContentPane().add(tRESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 75, -1));
        getContentPane().add(tPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Login.gif"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRESETActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Yakin ingin mereset form?",
        "Konfirmasi Reset",
        javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (confirm == javax.swing.JOptionPane.YES_OPTION){
            tUSERNAME.setText("");
            tPASSWORD.setText("");
            tUSERNAME.requestFocus();
        }
    }//GEN-LAST:event_tRESETActionPerformed

    private void tUSERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUSERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUSERNAMEActionPerformed

    private void tMASUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMASUKActionPerformed
       String tUSERNAMEInput = tUSERNAME.getText().trim();
       String tPASSWORDInput = String.valueOf(tPASSWORD()).trim();
       if (! tUSERNAMEInput.isEmpty() && !tPASSWORDInput.isEmpty()) {
           try {
               String sql = "SELECT * FROM user WHERE USERNAME=? AND userPassword=MD5(?) AND userStatus=1";
               Connection con = koneksi.connect();
               PreparedStatement ps = con.prepareStatement(sql);
               ps.setString(1,tUSERNAMEInput);
               ps.setString(2,tPASSWORDInput);
               
               ResultSet rs = ps.executeQuery();
               if (rs.next()){
                   String UserName = rs.getString("UserName");
                   String fullName = rs.getString("userFullName");
                   
                   Session.setUserName(UserName);
                   Session.setFullName(fullName); 
                   
                   dispose();
                   Home mainFrame = new Home();
                   mainFrame.setVisible(true);
                   
                  Home H = new Home();
                   mainFrame.getContentPane().add(H);
                   H.SetVisible(true);
               }else{
                   JOptionPane.showMessageDialog(null, "Login gagal! Username/Password salah atau akun tidak aktif!");
                   tPASSWORD.setText("");
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Error koneksi:" + e.getMessage());
           }
               
           
       }else{
           JOptionPane.showMessageDialog(null, "Kolom tidak boleh kosong!");
       }
    }//GEN-LAST:event_tMASUKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton tMASUK;
    private javax.swing.JPasswordField tPASSWORD;
    private javax.swing.JButton tRESET;
    private javax.swing.JTextField tUSERNAME;
    // End of variables declaration//GEN-END:variables

    private Object tPASSWORD() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
