/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simperkas;

import kelas.koneksi;
import kelas.Perkakas;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import static kelas.koneksi.connect;

/**
 *
 * @author Nabila
 */

public class panel_barang extends javax.swing.JPanel {

    DefaultTableModel modelTransaksi;

    /**
     * Creates new form panel_barang
     */
    public panel_barang() {
        initComponents();
        
        tJumlah.addActionListener(e -> bTambah.doClick());
        
    modelTransaksi = new DefaultTableModel();
        modelTransaksi.addColumn("ID Perkakas");
        modelTransaksi.addColumn("Nama Perkakas");
        modelTransaksi.addColumn("Jumlah");
        modelTransaksi.addColumn("Status");

        tbPerkakas.setModel(modelTransaksi);
        

        loadData();
    }

    private void loadData() {
        modelTransaksi.setRowCount(0);
        Perkakas pks = new Perkakas();
        try (ResultSet rs = pks.tampilBarang()) {
            while (rs != null && rs.next()) {
                modelTransaksi.addRow(new Object[]{
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getInt("jumlah"),
                    rs.getString("status")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        }
    }

    private void simpanData() {
        String nama = tNamaPerkakas.getText();
        int jumlah = Integer.parseInt(tJumlah.getText());
        String status;

        if (jumlah > 0) {
            status = "Tersedia";
        } else {
            status = "Tidak Tersedia";
        }

        try {
            Connection conn = connect();
            PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO barang (nama_barang, jumlah, status) VALUES (?, ?, ?)"
            );
            ps.setString(1, nama);
            ps.setInt(2, jumlah);
            ps.setString(3, status);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
            loadData();
            reset();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private String buatIdBarang() {
        String newId = "PM001";

        try (Connection conn = koneksi.connect()) {

            String sql = "SELECT id_barang FROM barang ORDER BY id_barang ASC";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            int expected = 1;

            while (rs.next()) {
                String id = rs.getString("id_barang");
                int num = Integer.parseInt(id.substring(2));

                if (num != expected) {
                    break;
                }

                expected++;
            }

            newId = String.format("PM%03d", expected);

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return newId;
    }

    private void cariData(String keyword) {
        modelTransaksi.setRowCount(0);
        try (Connection conn = connect(); PreparedStatement pst = conn.prepareStatement(
                "SELECT id_barang, nama_barang, jumlah, status FROM barang WHERE nama_barang LIKE ?")) {

            pst.setString(1, "%" + keyword + "%");

            try (ResultSet rs = pst.executeQuery()) {
                boolean ketemu = false;

                while (rs.next()) {
                    ketemu = true;
                    modelTransaksi.addRow(new Object[]{
                        rs.getString("id_barang"),
                        rs.getString("nama_barang"),
                        rs.getInt("jumlah"),
                        rs.getString("status")
                    });
                }
                if (!ketemu) {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                    loadData();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat mencari: " + e.getMessage());
        }
    }

    void reset() {
        tNamaPerkakas.setText(null);
        tJumlah.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNamaPerkakas = new javax.swing.JLabel();
        lJumlah = new javax.swing.JLabel();
        tNamaPerkakas = new javax.swing.JTextField();
        tJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPerkakas = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        lPerkakas = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNamaPerkakas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNamaPerkakas.setText("Nama Perkakas   :");
        add(lNamaPerkakas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlah.setText("Jumlah                 :");
        add(lJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        add(tNamaPerkakas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 590, 30));
        add(tJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 590, 30));

        tbPerkakas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPerkakas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPerkakasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPerkakas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 720, 280));

        bTambah.setBackground(new java.awt.Color(0, 51, 153));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, 30));

        bUbah.setBackground(new java.awt.Color(0, 51, 153));
        bUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 180, 30));

        bRefresh.setBackground(new java.awt.Color(0, 51, 153));
        bRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRefresh.setForeground(new java.awt.Color(255, 255, 255));
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 180, 30));

        bReset.setBackground(new java.awt.Color(0, 51, 153));
        bReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 180, 30));

        bHapus.setBackground(new java.awt.Color(204, 0, 51));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 170, 30));

        bCari.setBackground(new java.awt.Color(0, 51, 153));
        bCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCari.setForeground(new java.awt.Color(255, 255, 255));
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 170, 30));

        lPerkakas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Panel Barang.png"))); // NOI18N
        add(lPerkakas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        try {
            Perkakas pks = new Perkakas();
            pks.setIdBarang(buatIdBarang());
            pks.setNama(tNamaPerkakas.getText());
            pks.setJumlah(Integer.parseInt(tJumlah.getText()));
            pks.setJumlahAwal(Integer.parseInt(tJumlah.getText()));
            
            pks.setStatus(pks.getJumlah() > 0 ? "Tersedia" : "Tidak Tersedia");


            pks.tambahBarang();

            reset();
            loadData();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Isi semua kolom terlebih dahulu!");
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        int row = tbPerkakas.getSelectedRow(); 
if (row == -1) { 
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    try {
        String id = tbPerkakas.getValueAt(row, 0).toString();
        int jumlahSekarang = Integer.parseInt(tbPerkakas.getValueAt(row, 2).toString());
 
        Connection conn = connect();
        PreparedStatement ps = conn.prepareStatement(
            "SELECT jumlah_awal FROM barang WHERE id_barang=?"
        );
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int jumlahAwal = rs.getInt("jumlah_awal"); 
            if (jumlahSekarang < jumlahAwal) {
                JOptionPane.showMessageDialog(this,
                        "Data tidak dapat diubah!\nSebagian barang masih dipinjam.");
                return;
            }
        }

        Perkakas pks = new Perkakas();
        pks.setIdBarang(id);
        pks.setNama(tNamaPerkakas.getText());
        pks.setJumlah(Integer.parseInt(tJumlah.getText()));
        pks.setStatus(pks.getJumlah() > 0 ? "Tersedia" : "Tidak Tersedia");

        pks.ubahBarang();
        reset();
        loadData();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!");
    }
 
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        int row = tbPerkakas.getSelectedRow(); 
if (row == -1) { 
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    try {
        String id = tbPerkakas.getValueAt(row, 0).toString();

        Connection conn = connect();
        PreparedStatement ps = conn.prepareStatement(
            "SELECT jumlah, jumlah_awal, status FROM barang WHERE id_barang=?"
        );
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            int jumlah = rs.getInt("jumlah");
            int jumlahAwal = rs.getInt("jumlah_awal");
            String status = rs.getString("status");


            if (status.equalsIgnoreCase("Tidak Tersedia")) {
                JOptionPane.showMessageDialog(this,
                        "Data tidak dapat dihapus!\nBarang masih dipinjam.");
                return;
            }


            if (jumlah < jumlahAwal) {
                JOptionPane.showMessageDialog(this,
                        "Data tidak dapat dihapus!\nSebagian barang masih dipinjam.");
                return;
            }
        }

        Perkakas pks = new Perkakas();
        pks.setNama(tbPerkakas.getValueAt(row, 1).toString());
        pks.Hapus();

        loadData();
        reset();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
    }
 
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        reset();
    }//GEN-LAST:event_bResetActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        String keyword = JOptionPane.showInputDialog(this, "Masukkan Nama Perkakas:");

        if (keyword != null && !keyword.trim().isEmpty()) {
            cariData(keyword.trim());
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian terlebih dahulu!");
        }
    }//GEN-LAST:event_bCariActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        loadData();
    }//GEN-LAST:event_bRefreshActionPerformed

    private void tbPerkakasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPerkakasMouseClicked
        int row = tbPerkakas.getSelectedRow();
        if (row != -1) {
            tNamaPerkakas.setText(tbPerkakas.getValueAt(row, 1).toString());
        tJumlah.setText(tbPerkakas.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_tbPerkakasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lJumlah;
    private javax.swing.JLabel lNamaPerkakas;
    private javax.swing.JLabel lPerkakas;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNamaPerkakas;
    private javax.swing.JTable tbPerkakas;
    // End of variables declaration//GEN-END:variables
}
