/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simperkas;

/**
 *
 * @author Nabila
 */
public class panelTransaksii extends javax.swing.JPanel {

    /**
     * Creates new form panelTransaksi
     */
    public panelTransaksii() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNamaSantri = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        lNomorKamar = new javax.swing.JLabel();
        tNomorKamar = new javax.swing.JTextField();
        tJumlah = new javax.swing.JTextField();
        lJumlah = new javax.swing.JLabel();
        tNamaBarang = new javax.swing.JTextField();
        lNamaBarang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jdcTgl_Pinjam = new com.toedter.calendar.JDateChooser();
        jdcTgl_Kembali = new com.toedter.calendar.JDateChooser();
        lWaktuPinjam = new javax.swing.JLabel();
        lWaktuKembali = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bCetakPDF = new javax.swing.JButton();
        bResetData = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        lTransaksi = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNamaSantri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNamaSantri.setText("Nama Lengkap Santri   :");
        add(lNamaSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        tNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 90, -1));

        lNomorKamar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNomorKamar.setText("Nomor Kamar   :");
        add(lNomorKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        tNomorKamar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tNomorKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 340, -1));

        tJumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 90, -1));

        lJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lJumlah.setText("Jumlah Pinjam  :");
        add(lJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        tNamaBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 250, -1));

        lNamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lNamaBarang.setText("Nama Barang                :");
        add(lNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 740, 250));
        add(jdcTgl_Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, -1));
        add(jdcTgl_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 180, -1));

        lWaktuPinjam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lWaktuPinjam.setText("Waktu Peminjaman      :");
        add(lWaktuPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lWaktuKembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lWaktuKembali.setText("Waktu Pengembalian    :");
        add(lWaktuKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        bTambah.setBackground(new java.awt.Color(0, 51, 153));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambah.setForeground(new java.awt.Color(255, 255, 255));
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, -1));

        bUbah.setBackground(new java.awt.Color(0, 51, 153));
        bUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bUbah.setForeground(new java.awt.Color(255, 255, 255));
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 110, -1));

        bHapus.setBackground(new java.awt.Color(204, 0, 51));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 110, -1));

        bReset.setBackground(new java.awt.Color(0, 51, 153));
        bReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bReset.setForeground(new java.awt.Color(255, 255, 255));
        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        add(bReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 110, -1));

        bCetakPDF.setBackground(new java.awt.Color(0, 51, 153));
        bCetakPDF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCetakPDF.setForeground(new java.awt.Color(255, 255, 255));
        bCetakPDF.setText("Cetak PDF");
        bCetakPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakPDFActionPerformed(evt);
            }
        });
        add(bCetakPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, 30));

        bResetData.setBackground(new java.awt.Color(204, 0, 51));
        bResetData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bResetData.setForeground(new java.awt.Color(255, 255, 255));
        bResetData.setText("Reset Data");
        bResetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetDataActionPerformed(evt);
            }
        });
        add(bResetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 110, 30));

        bCari.setBackground(new java.awt.Color(0, 51, 153));
        bCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCari.setForeground(new java.awt.Color(255, 255, 255));
        bCari.setText("Cari");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });
        add(bCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 110, 30));

        bRefresh.setBackground(new java.awt.Color(0, 51, 153));
        bRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bRefresh.setForeground(new java.awt.Color(255, 255, 255));
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 110, 30));

        lTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Panel transaksi2.png"))); // NOI18N
        add(lTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCariActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHapusActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bResetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bResetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bResetDataActionPerformed

    private void bCetakPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCetakPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bCetakPDF;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bResetData;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdcTgl_Kembali;
    private com.toedter.calendar.JDateChooser jdcTgl_Pinjam;
    private javax.swing.JLabel lJumlah;
    private javax.swing.JLabel lNamaBarang;
    private javax.swing.JLabel lNamaSantri;
    private javax.swing.JLabel lNomorKamar;
    private javax.swing.JLabel lTransaksi;
    private javax.swing.JLabel lWaktuKembali;
    private javax.swing.JLabel lWaktuPinjam;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNamaBarang;
    private javax.swing.JTextField tNomorKamar;
    // End of variables declaration//GEN-END:variables
}
