/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simperkas;

import javax.swing.*;
import kelas.User;
import kelas.Session;

/**
 *
 * @author Nabila
 */
public class panelBerandaa extends javax.swing.JPanel {

    /**
     * Creates new form panelBerandaa
     */
    public panelBerandaa() {
        initComponents();
        tUsername.setText(Session.getUserName());
        tFullName.setText(Session.getFullName());
        tUsername.setEditable(false);
        tFullName.setEditable(false);
        tUsername.setFocusable(false);
        tFullName.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUsername = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        lFullName = new javax.swing.JLabel();
        tFullName = new javax.swing.JTextField();
        panelUtama = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lUsername.setForeground(new java.awt.Color(255, 255, 255));
        lUsername.setText("Username");
        add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        tUsername.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 220, 30));

        lFullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lFullName.setForeground(new java.awt.Color(255, 255, 255));
        lFullName.setText("Full Name");
        add(lFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        tFullName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        add(tFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 220, 30));

        panelUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Panel Utama new.png"))); // NOI18N
        add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lFullName;
    private javax.swing.JLabel lUsername;
    private javax.swing.JLabel panelUtama;
    private javax.swing.JTextField tFullName;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
